name: CI

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request:

jobs:
  lint:
    name: Lua lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install luacheck
        run: |
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck

      - name: Run luacheck
        run: luacheck .
